### ISSUE TITLE
Certain shows with multiple seasons download wrong season

### ISSUE THREAD

**Issue by watermelvin** [Benex254/FastAnime#6]
DLing Spy x Fam S2 with allanime results in files from S1.
server is set to Yt
Disabling automatic selection and manually choosing the correct season did not resolve. This can be verified by the first episode title being "Operation Strix" instead of the expected, "Follow Mama and Papa"
Any suggestions?

**Comment by Benex254** [comment]
Well this is because by default normalize_titles is set to true which tries and guesses the anime title you want by finding the one with the closest match to one retrieved using the anilist api. Then after it's done guessing it replaces the episode title with the one provided by the anilist api. I chose to implement this since there are multiple providers and wanted a consistent naming of downloads. However, you can turn off this feature by checking the config section on how to do so or tldr set normalize_titles to false either in your config file or as a cmdline option.

**Comment by watermelvin** [comment]
I actually did search for the exact title, and also reattempted with the auto select disabled and using the title taken directly from the search results.
Ex. 
```
fastanime download -t "Spy x Family Season 2"
``
What seems to be happening is that it downloads the correct season (Season 2), but then changes the episode titles to the wrong season (Season 1). I will keep normalize_titles as false for now, but it seems like there's an issue with getting episode titles from Anilist's API.

Should I mark this as closed and open a new issue for the anilist episode title mislabling?

As a sidenote, I do in fact have the completions installed, they help a lot with the commands.

**Comment by Benex254** [comment]
As I have initially said it guesses so theres a chance it may get it wrong though I have rarely encountered such. Unless the provider title is entirely different from those provided by anilist api. The process of getting the title is search for the anime title you passed in the cmdline, then if enabled search for the matched provider title using the anilist api then select the best match by comparing provider title and anilist anime results titles. So obviously in the process of matching, in case there's a big difference in the provider title for the anime and that of anilist, normalisation may wrongly label an episode. For example in allanime one piece is named as 1p.If you would like to help, since there's no way I can check for difference in titles across all anime titles between provider and anilist, either edit the data file as described in the docs or open an issue containing provider title and expected title. And if you have the completions there is no need to type out the whole title like you have done. For example start typing Spy then tabAnd it will show you possibilities of the anime title you want, uses the anilist api by the way. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Melvin Shajee ***@***.***> Date: 29/09/2024  22:06  (GMT+03:00) To: Benex254/FastAnime ***@***.***> Cc: BeneX254 ***@***.***>, Comment ***@***.***> Subject: Re: [Benex254/FastAnime] Certain shows with multiple seasons download wrong season (Issue #6) 
I actually did search for the exact title, and also reattempted with the auto select disabled and using the title taken directly from the search results.
Ex.
fastanime download -t "Spy x Family Season 2"

What seems to be happening is that it downloads the correct season (Season 2), but then changes the episode titles to the wrong season (Season 1). I will keep normalize_titles as false for now, but it seems like there's an issue with getting episode titles from Anilist's API.
Should I mark this as closed and open a new issue for the anilist episode title mislabling?
As a sidenote, I do in fact have the completions installed, they help a lot with the commands.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Benex254/FastAnime/issues/6#issuecomment-2381525688",
"url": "https://github.com/Benex254/FastAnime/issues/6#issuecomment-2381525688",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Benex254** [comment]
I have just confirmed with anilist api directly and found it is indeed the one to blame. 
```json
{
  "data": {
    "Page": {
      "media": [
        {
          "title": {
            "english": "SPY x FAMILY",
            "romaji": "SPY×FAMILY"
          },
          "streamingEpisodes": [
            {
              "title": "Episode 1 - OPERATION STRIX"
            },
            {
              "title": "Episode 2 - SECURE A WIFE"
            },
            {
              "title": "Episode 3 - PREPARE FOR THE INTERVIEW"
            },
            {
              "title": "Episode 4 - THE PRESTIGIOUS SCHOOL'S INTERVIEW"
            },
            {
              "title": "Episode 5 - WILL THEY PASS OR FAIL?"
            },
            {
              "title": "Episode 6 - THE FRIENDSHIP SCHEME"
            },
            {
              "title": "Episode 7 - THE TARGET'S SECOND SON"
            },
            {
              "title": "Episode 8 - THE COUNTER-SECRET POLICE COVER OPERATION"
            },
            {
              "title": "Episode 9 - SHOW OFF HOW IN LOVE YOU ARE"
            },
            {
              "title": "Episode 10 - THE GREAT DODGEBALL PLAN"
            },
            {
              "title": "Episode 11 - STELLA"
            },
            {
              "title": "Episode 12 - PENGUIN PARK"
            },
            {
              "title": "Episode 13 - PROJECT APPLE"
            },
            {
              "title": "Episode 14 - DISARM THE TIME BOMB"
            },
            {
              "title": "Episode 15 - A NEW FAMILY MEMBER"
            },
            {
              "title": "Episode 16 - YOR'S KITCHEN / THE INFORMANT'S GREAT ROMANCE PLAN"
            },
            {
              "title": "Episode 17 - CARRY OUT THE GRIFFIN PLAN / FULLMETAL LADY / OMELET RICE♥"
            },
            {
              "title": "Episode 18 - UNCLE THE PRIVATE TUTOR / DAYBREAK"
            },
            {
              "title": "Episode 19 - A REVENGE PLOT AGAINST DESMOND / MAMA BECOMES THE WIND"
            },
            {
              "title": "Episode 20 - INVESTIGATE THE GENERAL HOSPITAL / DECIPHER THE PERPLEXING CODE"
            },
            {
              "title": "Episode 21 - NIGHTFALL / FIRST FIT OF JEALOUSY"
            },
            {
              "title": "Episode 22 - THE UNDERGROUND TENNIS TOURNAMENT: THE CAMPBELLDON"
            },
            {
              "title": "Episode 23 - THE UNWAVERING PATH"
            },
            {
              "title": "Episode 24 - THE ROLE OF A MOTHER AND WIFE / SHOPPING WITH FRIENDS"
            },
            {
              "title": "Episode 25 - FIRST CONTACT"
            }
          ]
        },
        {
          "title": {
            "english": "SPY x FAMILY",
            "romaji": "SPY×FAMILY"
          },
          "streamingEpisodes": []
        },
        {
          "title": {
            "english": "Spy x Family: Family Portrait",
            "romaji": "SPYxFAMILY: Kazoku no Shouzou"
          },
          "streamingEpisodes": []
        },
        {
          "title": {
            "english": "SPY x FAMILY Season 2",
            "romaji": "SPY×FAMILY Season 2"
          },
          "streamingEpisodes": [
            {
              "title": "Episode 1 - OPERATION STRIX"
            },
            {
              "title": "Episode 2 - SECURE A WIFE"
            },
            {
              "title": "Episode 3 - PREPARE FOR THE INTERVIEW"
            },
            {
              "title": "Episode 4 - THE PRESTIGIOUS SCHOOL'S INTERVIEW"
            },
            {
              "title": "Episode 5 - WILL THEY PASS OR FAIL?"
            },
            {
              "title": "Episode 6 - THE FRIENDSHIP SCHEME"
            },
            {
              "title": "Episode 7 - THE TARGET'S SECOND SON"
            },
            {
              "title": "Episode 8 - THE COUNTER-SECRET POLICE COVER OPERATION"
            },
            {
              "title": "Episode 9 - SHOW OFF HOW IN LOVE YOU ARE"
            },
            {
              "title": "Episode 10 - THE GREAT DODGEBALL PLAN"
            },
            {
              "title": "Episode 11 - STELLA"
            },
            {
              "title": "Episode 12 - PENGUIN PARK"
            },
            {
              "title": "Episode 13 - PROJECT APPLE"
            },
            {
              "title": "Episode 14 - DISARM THE TIME BOMB"
            },
            {
              "title": "Episode 15 - A NEW FAMILY MEMBER"
            },
            {
              "title": "Episode 16 - YOR'S KITCHEN / THE INFORMANT'S GREAT ROMANCE PLAN"
            },
            {
              "title": "Episode 17 - CARRY OUT THE GRIFFIN PLAN / FULLMETAL LADY / OMELET RICE♥"
            },
            {
              "title": "Episode 18 - UNCLE THE PRIVATE TUTOR / DAYBREAK"
            },
            {
              "title": "Episode 19 - A REVENGE PLOT AGAINST DESMOND / MAMA BECOMES THE WIND"
            },
            {
              "title": "Episode 20 - INVESTIGATE THE GENERAL HOSPITAL / DECIPHER THE PERPLEXING CODE"
            },
            {
              "title": "Episode 21 - NIGHTFALL / FIRST FIT OF JEALOUSY"
            },
            {
              "title": "Episode 22 - THE UNDERGROUND TENNIS TOURNAMENT: THE CAMPBELLDON"
            },
            {
              "title": "Episode 23 - THE UNWAVERING PATH"
            },
            {
              "title": "Episode 24 - THE ROLE OF A MOTHER AND WIFE / SHOPPING WITH FRIENDS"
            },
            {
              "title": "Episode 25 - FIRST CONTACT"
            }
          ]
        },
        {
          "title": {
            "english": "SPY x FAMILY Cour 2",
            "romaji": "SPY×FAMILY Part 2"
          },
          "streamingEpisodes": []
        },
        {
          "title": {
            "english": "SPY x FAMILY CODE: White",
            "romaji": "SPY×FAMILY CODE: White"
          },
          "streamingEpisodes": []
        },
        {
          "title": {
            "english": "Four Lives Remain: Tatsuya Endo Before Spy x Family",
            "romaji": "Shihou Yuugi: Endou Tatsuya Tanpenshuu"
          },
          "streamingEpisodes": []
        },
        {
          "title": {
            "english": "Street Fighter 6 VS SPY×FAMILY CODE: White",
            "romaji": "Street Fighter 6 × SPY×FAMILY CODE: White"
          },
          "streamingEpisodes": []
        }
      ]
    }
  }
}
```
I can't do anything about this one. So am going to close it as completed unless you have anything to add?

**Comment by watermelvin** [comment]
Nope, sounds good. Thank you for your time.
